Selenium/Models/Currency.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Selenium.Models
{
    public class Currency
    {
        [Key]
		[Description("Primary Key")]
		public int CurrencyID { get; set; }

		[Required]
		[StringLength(3)]
		[Description("ISO Code")]
		public string ISOCode { get; set; }

		[Required]
		[StringLength(250)]
		[Description("Name")]
		public string Name { get; set; }

		[Required]
		[StringLength(3)]
		[Description("Numeric ISO Code")]
		public string NumericISOCode { get; set; }

		[Required]
		[StringLength(100)]
		[Description("Symbol")]
        public string Symbol { get; set; }

		[StringLength(100)]
		[Description("System Code")]
		public string SystemCode { get; set; }

		[Required]
		[Description("Units")]
		[StringLength(100)]
		public string Units { get; set; }
    }
}

Selenium/Models/ErrorViewModel.cs
using System;

namespace Selenium.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Selenium/Controllers/CurrencyController.cs
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Selenium.Data;
using Selenium.DTOs;
using Selenium.Models;
using System;
using System.Threading.Tasks;

namespace Selenium.Controllers
{
    public class CurrencyController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IMapper _mapper;

        public CurrencyController(ApplicationDbContext db, IMapper mapper)
        {
            _db = db;
            _mapper = mapper;
        }

        // GET Action Method
        public async Task<IActionResult> Index()
        {
            var currencies = await _db.Currencies.ToListAsync();
            return View(currencies);
        }

        ///  GET - CREATE
        public IActionResult Create()
        {
            return View();
        }

        // POST - CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CurrencyCreateRequest request)
        {
            if (ModelState.IsValid)
            {
                var req = _mapper.Map<Currency>(request);
                _db.Currencies.Add(req);
                await _db.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            return View(request);
        }

        // GET - VIEW
        public async Task<IActionResult> Details(int? ID)
        {
            if (ID == null)
            {
                return NotFound();
            }

            var Currencies = await _db.Currencies.SingleOrDefaultAsync(x => x.CurrencyID == ID);
            if (Currencies == null)
            {
                return NotFound();
            }
            return View(Currencies);
        }

        // GET - EDIT
        public async Task<IActionResult> Edit(int? ID)
        {
            if (ID == null)
            {
                return NotFound();
            }

            var currencies = await _db.Currencies.SingleOrDefaultAsync(x => x.CurrencyID == ID);
            if (currencies == null)
            {
                return NotFound();
            }
            return View(currencies);
        }

        // POST - EDIT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(CurrencyUpdateRequest request)
        {
            var original = await _db.Currencies.SingleOrDefaultAsync(x => x.Symbol == request.Symbol);

            if (original != null)
            {
                _mapper.Map(request, original);
                await _db.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            //if (ModelState.IsValid)
            //{
            //    _db.Update(request);
            //    await _db.SaveChangesAsync();
            //    return RedirectToAction(nameof(Index));
            //}

            return View(_mapper.Map<CurrencyDTO>(original));
        }

        // POST - DELETE
        public async Task<IActionResult> Delete(int? ID)
        {
            if (ID == null)
            {
                return NotFound();
            }

            var currencies = await _db.Currencies.FindAsync(ID);
            if (currencies == null)
            {
                return NotFound();
            }
            return View(currencies);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? ID)
        {
            var currencies = await _db.Currencies.FindAsync(ID);

            if (currencies == null)
            {
                return View();
            }
            _db.Currencies.Remove(currencies);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Selenium/Views/Currency/Create.cshtml
@model Currency
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<h2 class="text-info">Create Currency</h2>
<br />

<form method="post" asp-action="Create">
    <div class="border bg-light p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="ISOCode" class="col-form-label"></label>
            </div>
            <div class="col-5">
                <input asp-for="ISOCode" id="Create-Currency-ISOCode" class="form-control" />
            </div>
            <span asp-validation-for="ISOCode" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="Name" class="col-form-label"></label>
            </div>
            <div class="col-5">
                <input asp-for="Name" id="Create-Currency-Name" class="form-control" />
            </div>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="NumericISOCode" class="col-form-label"></label>
            </div>
            <div class="col-5">
                <input asp-for="NumericISOCode" id="Create-Currency-NumericISOCode" class="form-control" />
            </div>
            <span asp-validation-for="NumericISOCode" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="Symbol" class="col-form-label"></label>
            </div>
            <div class="col-5">
                <input asp-for="Symbol" id="Create-Currency-Symbol" class="form-control" />
            </div>
            <span asp-validation-for="Symbol" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="SystemCode" class="col-form-label"></label>
            </div>
            <div class="col-5">
                <input asp-for="SystemCode" id="Create-Currency-SystemCode" class="form-control" />
            </div>
            <span asp-validation-for="SystemCode" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="Units" class="col-form-label"></label>
            </div>
            <div class="col-5">
                <input asp-for="Units" id="Create-Currency-Units" class="form-control" />
            </div>
            <span asp-validation-for="Units" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-5 offset-2">
                <partial name="_CreateAndBackToListButton" />
            </div>
        </div>
    </div>
</form>

Selenium/Views/Currency/Delete.cshtml
@model Selenium.Models.Currency

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<h2 class="text-info">Delete Currency</h2>
<br />

<form method="post" asp-action="Delete">
    <div class="border bg-light p-3">
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="ISOCode" class="col-form-label"></label>
            </div>
            <div class="col-5">
                <input asp-for="ISOCode"  readonly class="form-control" />
            </div>
            <span asp-validation-for="ISOCode" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="Name" class="col-form-label"></label>
            </div>
            <div class="col-5">
                <input asp-for="Name"  readonly class="form-control" />
            </div>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="NumericISOCode" class="col-form-label"></label>
            </div>
            <div class="col-5">
                <input asp-for="NumericISOCode"  readonly class="form-control" />
            </div>
            <span asp-validation-for="NumericISOCode" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="Symbol" class="col-form-label"></label>
            </div>
            <div class="col-5">
                <input asp-for="Symbol"  readonly class="form-control" />
            </div>
            <span asp-validation-for="Symbol" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="SystemCode" class="col-form-label"></label>
            </div>
            <div class="col-5">
                <input asp-for="SystemCode"  readonly class="form-control" />
            </div>
            <span asp-validation-for="SystemCode" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="Units" class="col-form-label"></label>
            </div>
            <div class="col-5">
                <input asp-for="Units"  readonly class="form-control" />
            </div>
            <span asp-validation-for="Units" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-5 offset-2">
                <partial name="_DeleteAndBackToListButton" model="Model.CurrencyID" />
            </div>
        </div>
    </div>
</form>

Selenium/Views/Currency/Details.cshtml
@model Selenium.Models.Currency

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<h2 class="text-info">Details Currency</h2>
<br />

<form method="post" asp-action="Details">
    <div class="border bg-light p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="ISOCode" class="col-form-label"></label>
            </div>
            <div class="col-5">
                <input asp-for="ISOCode"  readonly class="form-control" />
            </div>
            <span asp-validation-for="ISOCode" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="Name" class="col-form-label"></label>
            </div>
            <div class="col-5">
                <input asp-for="Name"  readonly class="form-control" />
            </div>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="NumericISOCode" class="col-form-label"></label>
            </div>
            <div class="col-5">
                <input asp-for="NumericISOCode"  readonly class="form-control" />
            </div>
            <span asp-validation-for="NumericISOCode" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="Symbol" class="col-form-label"></label>
            </div>
            <div class="col-5">
                <input asp-for="Symbol"  readonly class="form-control" />
            </div>
            <span asp-validation-for="Symbol" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="SystemCode" class="col-form-label"></label>
            </div>
            <div class="col-5">
                <input asp-for="SystemCode"  readonly class="form-control" />
            </div>
            <span asp-validation-for="SystemCode" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="Units" class="col-form-label"></label>
            </div>
            <div class="col-5">
                <input asp-for="Units"  readonly class="form-control" />
            </div>
            <span asp-validation-for="Units" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-5 offset-2">
                <partial name="_ViewAndBackToListButton" model="Model.CurrencyID" />
            </div>
        </div>
    </div>
</form>

Selenium/Views/Currency/Edit.cshtml
@model Selenium.Models.Currency

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<h2 class="text-info">Edit Currency</h2>
<br />

<form method="post" asp-action="Edit">
    <div class="border bg-light p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="ISOCode" class="col-form-label"></label>
            </div>
            <div class="col-5">
                <input asp-for="ISOCode" id="Update-Currency-ISOCode" class="form-control" />
            </div>
            <span asp-validation-for="ISOCode" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="Name" class="col-form-label"></label>
            </div>
            <div class="col-5">
                <input asp-for="Name" id="Update-Currency-Name" class="form-control" />
            </div>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="NumericISOCode" class="col-form-label"></label>
            </div>
            <div class="col-5">
                <input asp-for="NumericISOCode" id="Update-Currency-NumericISOCode" class="form-control" />
            </div>
            <span asp-validation-for="NumericISOCode" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="SystemCode" class="col-form-label"></label>
            </div>
            <div class="col-5">
                <input asp-for="SystemCode" id="Update-Currency-SystemCode" class="form-control" />
            </div>
            <span asp-validation-for="SystemCode" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="Symbol" class="col-form-label"></label>
            </div>
            <div class="col-5">
                <input asp-for="Symbol" id="Update-Currency-Symbol" class="form-control" />
            </div>
            <span asp-validation-for="Symbol" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="Units" class="col-form-label"></label>
            </div>
            <div class="col-5">
                <input asp-for="Units" id="Update-Currency-Units" class="form-control" />
            </div>
            <span asp-validation-for="Units" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-5 offset-2">
                <div class="row">
                    <div class="col-6">
                        <input type="submit" id="Update-Currency-Button" class="btn btn-info form-control" asp-route-id="@Model" value="Update" />
                    </div>
                    <div class="col-6">
                        <a asp-action="Index" class="btn btn-success form-control">Back To List</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

Selenium/Views/Currency/Index.cshtml
@model IEnumerable<Currency>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br /><br />
<div class="border bg-light p-3">
    <div class="row">
        <div class="col-6">
            <h2 class="text-info">Currency List</h2>
        </div>
        <div class="col-6 text-right">
            <partial name="_CreateButtonPartial" />
        </div>
    </div>
    <br />
    <div>
        @if(Model.Count() > 0)
        {
            <table class="table table-striped border">
                <tr class="table-secondary">
                    <th>
                        @Html.DisplayNameFor(m => m.ISOCode)
                    </th>
                    <th>
                        @Html.DisplayNameFor(m => m.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(m => m.NumericISOCode)
                    </th>
                    <th>
                        @Html.DisplayNameFor(m => m.Symbol)
                    </th>
                    <th></th>
                </tr>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(m => item.ISOCode)
                        </td>
                        <td>
                            @Html.DisplayFor(m => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(m => item.NumericISOCode)
                        </td>
                        <td>
                            @Html.DisplayFor(m => item.Symbol)
                        </td>
                        <td style="width: 150px">
                            <div class="btn-group" role="group">
                                <a id="Update-Currency-@item.Symbol-1" class="btn btn-primary text-white" asp-action="Edit" asp-route-id="@item.CurrencyID">
                                    <i class="fas fa-edit" aria-hidden="true">Update</i>
                                </a>
                                <a id="Detail-Currency-@item.Symbol-2" class="btn btn-success text-white" asp-action="Details" asp-route-id="@item.CurrencyID">
                                    <i class="bi bi-list" aria-hidden="true">View</i>
                                </a>
                                <a id="Delete-Currency-@item.Symbol-3" class="btn btn-danger text-white" asp-action="Delete" asp-route-id="@item.CurrencyID">
                                    <i class="bi-trash" aria-hidden="true">Delete</i>
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </table>
        }
        else
        {
            <p>No Category exists</p>
        }
    </div>
</div>

Selenium/Views/Shared/_CreateAndBackToListButton.cshtml
<div class="row">
    <div class="col-6">
        <input type="submit" id="Create-Currency-Button" class="btn btn-info form-control" value="Create" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back To List</a>
    </div>
</div>

Selenium/Views/Shared/_CreateButtonPartial.cshtml
<p>
    <a asp-action="Create" id="Create-Currency" class="btn btn-info"><i class="fa fa-plus" aria-hidden="true"></i> &nbsp; Create Button</a>
</p>

Selenium/Views/Shared/_DeleteAndBackToListButton.cshtml
@model int

<div class="row">
    <div class="col-6">
        <input type="submit" id="Delete-Currency-Button" class="btn btn-danger form-control" asp-route-id="@Model" value="Delete" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back To List</a>
    </div>
</div>

Selenium/Views/Shared/_DetailAndBackToListButton.cshtml
@model int
<div class="row">
    <div class="col-6">
        <a asp-action="Index" id="Detail-Currency-Back" class="btn btn-success form-control">Back To List</a>
    </div>
</div>

Selenium/Views/Shared/_EditAndBackToListButton.cshtml
@model int
<div class="row">
    <div class="col-6">
        <input type="submit" id="Update-Currency-Button-@Model." class="btn btn-info form-control" asp-route-id="@Model" value="Update" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back To List</a>
    </div>
</div>

Selenium/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Selenium</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Currency" asp-action="Index">Selenium</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Currency" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Selenium - <a asp-area="" asp-controller="Currency" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Selenium/Views/Shared/_TableButtonPartial.cshtml
@model int

<td style="width: 150px">
    <div class="btn-group" role="group">
        <a id="Update-Currency-@Model" class="btn btn-primary text-white" asp-action="Edit" asp-route-Id="@Model">
            <i class="fas fa-edit" aria-hidden="true"></i>
        </a>
        <a id="Update-Currency-@Model" class="btn btn-success text-white" asp-action="Details" asp-route-Id="@Model">
            <i class="bi bi-list" aria-hidden="true"></i>
        </a>
        <a id="Update-Currency-@Model" class="btn btn-danger text-white" asp-action="Delete" asp-route-Id="@Model">
            <i class="bi-trash" aria-hidden="true"></i>
        </a>
    </div>
</td>

Selenium/Views/Shared/_ViewAndBackToListButton.cshtml
@model int
<div class="row">
    <div class="col-6">
        <a asp-action="Index" id="View-Currency-BackButton" class="btn btn-success form-control">Back To List</a>
    </div>
</div>